Fix -Wo-address-of-packed-member warnings (armgcc >= 9)
nxp-mcuxpresso/mcux-sdk-examples pull request #3
Opened 2021-06-18 14:25 UTC by Hadatko

Signed-off-by: Cervenka Dusan <cervenka@acrios.com>

2021-06-28 05:53 UTC, zejiang0jason requested changes

2021-06-28 05:53 UTC, zejiang0jason commented on evkmcimx7ulp/demo_apps/wireless_uart_bridge/srtm/services/srtm_pmic_service.c
> +                tmpOutValue = pmicResp->value;
should be `pmicResp->value = tmpOutValue`. Similar issue for other modifications except `rtcResp->alarm.seconds = tmpOutSeconds;`

2021-06-28 20:23 UTC, Hadatko commented on evkmcimx7ulp/demo_apps/wireless_uart_bridge/srtm/services/srtm_pmic_service.c
> +                tmpOutValue = pmicResp->value;
Hi sorry for this error. Night work. I will fix it immediately

2021-06-28 20:38 UTC, Hadatko commented
Is it ok now?

2021-06-29 03:10 UTC, zejiang0jason approved these changes

2021-06-29 03:13 UTC, merged